# xarray hands-on

In [2]:
import os
import urllib
import pandas as pd
import numpy as np

import xarray as xr   # This is the package we'll explore

In [ ]:
temp_data = np.array(
    [np.zeros([5,5]),
     np.ones([5,5]),
     #np.ones((5,5)), argument here can be a tuple or a list
     np.ones([5,5])*2]).astype(int)

temp_data

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])

In [7]:
dims = ('time', 'lat', 'lon')

coords = {
    'time' : pd.date_range('2022-09-01', '2022-09-03'),
    'lat' : np.arange(70, 20, -10), 
    'lon' : np.arange(60, 110, 10)
}


In [5]:
attrs = {
    'title': 'temperature across stations', 
    'standard_name': 'air_temperature', 
    'units': 'degree_c'
}

In [8]:
temp = xr.DataArray(data = temp_data,
                    dims = dims, 
                    coords = coords,
                    attrs = attrs)

temp

<xarray.DataArray (time: 3, lat: 5, lon: 5)> Size: 600B
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])
Coordinates:
  * time     (time) datetime64[ns] 24B 2022-09-01 2022-09-02 2022-09-03
  * lat      (lat) int64 40B 70 60 50 40 30
  * lon      (lon) int64 40B 60 70 80 90 100
Attributes:
    title:          temperature across stations
    standard_name:  air_temperature
    units:          degree_c

In [11]:
temp.attrs['description'] = 'simple example of xarray'

temp

<xarray.DataArray (time: 3, lat: 5, lon: 5)> Size: 600B
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])
Coordinates:
  * time     (time) datetime64[ns] 24B 2022-09-01 2022-09-02 2022-09-03
  * lat      (lat) int64 40B 70 60 50 40 30
  * lon      (lon) int64 40B 60 70 80 90 100
Attributes:
    title:          temperature across stations
    standard_name:  air_temperature
    units:          degree_c
    description:    simple example of xarray

In [12]:
temp.lat.attrs = {
    'description': 'latitude', 
    'standard_name': 'grid_latitude',
    'units': 'degrees_N'
}

temp

<xarray.DataArray (time: 3, lat: 5, lon: 5)> Size: 600B
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])
Coordinates:
  * time     (time) datetime64[ns] 24B 2022-09-01 2022-09-02 2022-09-03
  * lat      (lat) int64 40B 70 60 50 40 30
  * lon      (lon) int64 40B 60 70 80 90 100
Attributes:
    title:          temperature across stations
    standard_name:  air_temperature
    units:          degree_c
    description:    simple example of xarray

In [17]:
#temp.loc['2022-09-01',:,:]
temp.sel(time = '2022-09-01', lat = 50)
temp.sel(lon = slice(60,80), time = '2022-09-01')

<xarray.DataArray (lat: 5, lon: 3)> Size: 120B
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])
Coordinates:
    time     datetime64[ns] 8B 2022-09-01
  * lat      (lat) int64 40B 70 60 50 40 30
  * lon      (lon) int64 24B 60 70 80
Attributes:
    title:          temperature across stations
    standard_name:  air_temperature
    units:          degree_c
    description:    simple example of xarray

In [20]:
temp.mean(dim = 'time')
temp.mean(dim = ( 'time', 'lat'))

<xarray.DataArray (lon: 5)> Size: 40B
array([1., 1., 1., 1., 1.])
Coordinates:
  * lon      (lon) int64 40B 60 70 80 90 100

In [22]:
temp.to_dataset(name = 'temperature')

<xarray.Dataset> Size: 704B
Dimensions:      (time: 3, lat: 5, lon: 5)
Coordinates:
  * time         (time) datetime64[ns] 24B 2022-09-01 2022-09-02 2022-09-03
  * lat          (lat) int64 40B 70 60 50 40 30
  * lon          (lon) int64 40B 60 70 80 90 100
Data variables:
    temperature  (time, lat, lon) int64 600B 0 0 0 0 0 0 0 0 ... 2 2 2 2 2 2 2 2

In [27]:
avg_temp = temp.mean(dim = 'time')

data_vars = {
    'temp': temp, 
    'avg_temp': avg_temp
}

attrs = {
    'title' : 'temperature data'
}

temp_dataset = xr.Dataset(data_vars = data_vars, attrs = attrs)

temp_dataset

<xarray.Dataset> Size: 904B
Dimensions:   (time: 3, lat: 5, lon: 5)
Coordinates:
  * time      (time) datetime64[ns] 24B 2022-09-01 2022-09-02 2022-09-03
  * lat       (lat) int64 40B 70 60 50 40 30
  * lon       (lon) int64 40B 60 70 80 90 100
Data variables:
    temp      (time, lat, lon) int64 600B 0 0 0 0 0 0 0 0 0 ... 2 2 2 2 2 2 2 2
    avg_temp  (lat, lon) float64 200B 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0
Attributes:
    title:    temperature data

In [35]:
temp_dataset.plot()

ValueError: Dataset.plot cannot be called directly. Use an explicit plot method, e.g. ds.plot.scatter(...)

In [30]:
fp = os.path.join(os.getcwd(),'temp_dataset.nc')
fp

temp_dataset.to_netcdf(fp)

In [ ]:
check = xr.open_dataset(fp)
check == temp_dataset # this checks values

xr.open_dataset(fp).equals(temp_dataset) # this evaluates the entire file

True

# Exercise from course book

In [36]:

url = 'https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A792bfc37-416e-409e-80b1-fdef8ab60033'

msg = urllib.request.urlretrieve(url, "FW_data_CESM_LW_2006_2100.nc")

In [37]:
fp = os.path.join(os.getcwd(),'FW_data_CESM_LW_2006_2100.nc')
fw_data = xr.open_dataset(fp)
fw_data

<xarray.Dataset> Size: 135kB
Dimensions:                          (time: 95, member: 11)
Coordinates:
  * time                             (time) float64 760B 2.006e+03 ... 2.1e+03
  * member                           (member) float64 88B 1.0 2.0 ... 10.0 11.0
Data variables: (12/16)
    FW_flux_Fram_annual_net          (time, member) float64 8kB ...
    FW_flux_Barrow_annual_net        (time, member) float64 8kB ...
    FW_flux_Nares_annual_net         (time, member) float64 8kB ...
    FW_flux_Davis_annual_net         (time, member) float64 8kB ...
    FW_flux_BSO_annual_net           (time, member) float64 8kB ...
    FW_flux_Bering_annual_net        (time, member) float64 8kB ...
    ...                               ...
    Solid_FW_flux_BSO_annual_net     (time, member) float64 8kB ...
    Solid_FW_flux_Bering_annual_net  (time, member) float64 8kB ...
    runoff_annual                    (time, member) float64 8kB ...
    netPrec_annual                   (time, member) float64 8kB ...
    Liquid_FW_storage_Arctic_annual  (time, member) float64 8kB ...
    Solid_FW_storage_Arctic_annual   (time, member) float64 8kB ...
Attributes:
    creation_date:   02-Jun-2020 15:38:31
    author:          Alexandra Jahn, CU Boulder, alexandra.jahn@colorado.edu
    title:           Annual timeseries of freshwater data from the CESM Low W...
    description:     Annual mean Freshwater (FW) fluxes and storage relative ...
    data_structure:  The data structure is |Ensemble member | Time (in years)...

In [38]:
fw_data.runoff_annual

<xarray.DataArray 'runoff_annual' (time: 95, member: 11)> Size: 8kB
[1045 values with dtype=float64]
Coordinates:
  * time     (time) float64 760B 2.006e+03 2.007e+03 ... 2.099e+03 2.1e+03
  * member   (member) float64 88B 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0
Attributes:
    units:      km3/yr
    long_name:  FW flux from river runoff into the Arctic Ocean domain, relat...

In [41]:
fw_data.runoff_annual.sel(member = 2.1, method = 'nearest')

<xarray.DataArray 'runoff_annual' (time: 95)> Size: 760B
[95 values with dtype=float64]
Coordinates:
  * time     (time) float64 760B 2.006e+03 2.007e+03 ... 2.099e+03 2.1e+03
    member   float64 8B 2.0
Attributes:
    units:      km3/yr
    long_name:  FW flux from river runoff into the Arctic Ocean domain, relat...

# Tables <--> Arrays

In [4]:
temp_pd = pd.read_csv('/home/mloranty/scalable-computing-examples/data/netcdf_temp_data.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/home/mloranty/scalable-computing-examples/data/netcdf_temp_data.csv'